### ISSUE TITLE
Change density in ggpattern plots

### ISSUE THREAD

**Issue by mellisbirds** [trevorld/gridpattern#66]
Hi,

Very fun package. Do you have any tips for changing polygon tiling density in plots produced with ggpattern? I haven't been able to find a way to make tiles larger or smaller using gridpattern's density argument or ggpattern's pattern_density argument. 

Thanks!
Mike

**Comment by trevorld** [comment]
For the `polygon_tiling` pattern you should use `pattern_spacing` to make
the polygons bigger or smaller.  For that pattern we auto-set the density
for each component subpattern so that the polygons tile so it isn't a
user-settable parameter...
https://trevorldavis.com/R/gridpattern/reference/grid.pattern_polygon_tiling.html
